### ISSUE TITLE
stopAnimation not fully replacing old text!

### ISSUE THREAD

**Issue by EmeraldMike** [SkylixGH/NitroJS#5] opened 2022-01-18 16:42 UTC
So when using `terminal.animate("Long text the text")` and then `terminal.stopAnimation(State.error, "short text")` you get something like `short text he text` basically combining the 2.
demo code
```
import terminal, { State } from "@skylixgh/nitrojs-terminal";

terminal.animate("Meow meow")

setTimeout(() => {
    terminal.stopAnimation(State.error,"Meow")
},2000)

```
expected: Meow
Get: Meow meow

**Comment by EmeraldMike** [comment] 2022-01-18 18:04
`terminal.updateAnimation()`
however does not fall victim to this issue

**Comment by EmeraldMike** [comment] 2022-01-18 18:06
Also the un overwritten text keeps their color when stopping the animation.

**Comment by XFaonAE** [comment] 2022-01-19 02:30
This has been confirmed to only happen in NitroJS node enviorment
The bug is happening because the NitroJS execution proxy is not piping correctly

**Comment by MelonFruit7** [comment] 2022-01-29 01:29
Fixed in v2

**Closed by MelonFruit7** 2022-01-29 01:29 UTC
Labels: bug, good first issue
